public class demo {
  integer i=10;

 public static void main(){
     demo a1 = new demo();
     demo a2 = new demo();
     demo a3 = new demo();
     demo a4 = new demo();
     demo a5 = new demo();
     demo a6 = new demo();
  a1.i=11;
  a2.i=12;
  a3.i=13;
  a4.i=14;
  a5.i=15;
  a6.i=16;
System.debug(a1.i);
System.debug(a2.i);
System.debug(a3.i);
System.debug(a4.i);
System.debug(a5.i);
System.debug(a6.i);
 }

}